/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AiReceptionistSwitzerlandRouteImport } from './routes/ai-receptionist-switzerland'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as RSlugCallRouteImport } from './routes/r.$slug.call'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AiReceptionistSwitzerlandRoute =
  AiReceptionistSwitzerlandRouteImport.update({
    id: '/ai-receptionist-switzerland',
    path: '/ai-receptionist-switzerland',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugCallRoute = RSlugCallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => RSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-receptionist-switzerland': typeof AiReceptionistSwitzerlandRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/r/$slug/call': typeof RSlugCallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-receptionist-switzerland': typeof AiReceptionistSwitzerlandRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/r/$slug/call': typeof RSlugCallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-receptionist-switzerland': typeof AiReceptionistSwitzerlandRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/r/$slug/call': typeof RSlugCallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-receptionist-switzerland'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/r/$slug'
    | '/r/$slug/call'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-receptionist-switzerland'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/r/$slug'
    | '/r/$slug/call'
  id:
    | '__root__'
    | '/'
    | '/ai-receptionist-switzerland'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/r/$slug'
    | '/r/$slug/call'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiReceptionistSwitzerlandRoute: typeof AiReceptionistSwitzerlandRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RSlugRoute: typeof RSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-receptionist-switzerland': {
      id: '/ai-receptionist-switzerland'
      path: '/ai-receptionist-switzerland'
      fullPath: '/ai-receptionist-switzerland'
      preLoaderRoute: typeof AiReceptionistSwitzerlandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug/call': {
      id: '/r/$slug/call'
      path: '/call'
      fullPath: '/r/$slug/call'
      preLoaderRoute: typeof RSlugCallRouteImport
      parentRoute: typeof RSlugRoute
    }
  }
}

interface RSlugRouteChildren {
  RSlugCallRoute: typeof RSlugCallRoute
}

const RSlugRouteChildren: RSlugRouteChildren = {
  RSlugCallRoute: RSlugCallRoute,
}

const RSlugRouteWithChildren = RSlugRoute._addFileChildren(RSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiReceptionistSwitzerlandRoute: AiReceptionistSwitzerlandRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RSlugRoute: RSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
